### ISSUE TITLE
Add a semantic for Windows Registry Keys

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-generator#19] opened 2021-06-24 21:24 UTC
Current implementation will fail in the stix validator.

**Comment by chisholm** [comment] 2021-09-15 01:57
I think the cause of this failure is the same as https://github.com/oasis-open/cti-stix-validator/issues/185 in the stix validator.  That should be fixed by the schema fix at https://github.com/oasis-open/cti-stix2-json-schemas/pull/144 .  So we decided it's a validator issue, not a generator issue.  (Which in turn boiled down to a JSON Schema issue.)  I'll add a "fixes" clause to cause this issue to close when that PR is merged.

**Closed as completed** 2021-09-29 17:49 UTC
